<?php

namespace Ibrows\DataTrans;

class Constants
{
    const version = '8.41';

    const URL_AUTHORIZATION = 'https://payment.datatrans.biz/upp/jsp/upStart.jsp';
    const URL_XMLSETTLEMENT = 'https://payment.datatrans.biz/upp/jsp/XML_processor.jsp';

    const STATUS_SUCCESS = 'success';
    const STATUS_ERROR = 'error';
    const STATUS_CANCEL = 'cancel';

    const MSGTYPE_GET = 'web';
    const MSGTYPE_POST = 'post';

    const PAYMENTMETHOD_VISA = 'VIS';
    const PAYMENTMETHOD_MASTERCARD = 'ECA';
    const PAYMENTMETHOD_AMERICANEXPRESS = 'AMX';
    const PAYMENTMETHOD_BILLPAY = 'BPY';
    const PAYMENTMETHOD_BILLSAFE = 'BSF';
    const PAYMENTMETHOD_CURABILL = 'CUR';
    const PAYMENTMETHOD_DINERSCLUB_DISCOVER = 'DIN';
    const PAYMENTMETHOD_IDEAL = 'DEA';
    const PAYMENTMETHOD_SOFORTUEBERWEISUNG = 'DIB';
    const PAYMENTMETHOD_IDEALVIASOFORTUEBERWEISUNG = 'DII';
    const PAYMENTMETHOD_DANKORT = 'DNK';
    const PAYMENTMETHOD_DELTAVISTA = 'DVI';
    const PAYMENTMETHOD_GERMANELV = 'ELV';
    const PAYMENTMETHOD_ESPONLINEUEBERWEISUNG = 'ESP';
    const PAYMENTMETHOD_SWISSCOMEASYPAY = 'ESY';
    const PAYMENTMETHOD_JCB = 'JCB';
    const PAYMENTMETHOD_JELMOLIBONUSCARD = 'JEL';
    const PAYMENTMETHOD_MAESTRO = 'MAU';
    const PAYMENTMETHOD_MEDIAMARKTSHOPPINGCARD = 'MMS';
    const PAYMENTMETHOD_MFGROUPCHECKOUT = 'MFA';
    const PAYMENTMETHOD_MFGROUPFINANCIALREQUEST = 'MFG';
    const PAYMENTMETHOD_MFGROUPEASYINTEGRATION = 'MFX';
    const PAYMENTMETHOD_MONEYBOOKERS = 'MNB';
    const PAYMENTMETHOD_PAYPAL = 'PAP';
    const PAYMENTMETHOD_SWISSPOSTFINANCEEFINANCE = 'PEF';
    const PAYMENTMETHOD_SWISSPOSTFINANCECARD = 'PFC';
    const PAYMENTMETHOD_PAYSAFECARD = 'PSC';
    const PAYMENTMETHOD_CASHTICKET = 'PST';
    const PAYMENTMETHOD_PAYOLUTIONINSTALLMENTS = 'PYL';
    const PAYMENTMETHOD_PAYOLUTIONINVOICE = 'PYO';
    const PAYMENTMETHOD_REKACARD = 'REK';
    const PAYMENTMETHOD_SWISSBILLING = 'SWB';
    const PAYMENTMETHOD_SATURNWINNERCARD = 'SWC';
}
